services:
  certbot:
    image: ghcr.io/johnnylin-a/le-cert-maker:latest
    # build:
    #   context: .
    restart: unless-stopped
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - /var/lib/letsencrypt:/var/lib/letsencrypt
      - /usr/share/nginx/html:/webroot
      - ./.auth.ini:/root/.auth.ini:ro
      - ./deploy-hook.sh:/deploy-hook.sh:ro
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew --deploy-hook \"/bin/sh -c /deploy-hook.sh\"; sleep 24h & wait $${!}; done;'"
